dist: trusty

env:
  - DOCKER_USERNAME=agileraymond

jobs:
  include:
    - stage: build docker image
      script:
      - set 
      - docker login -u $DOCKER_USERNAME -p RaY246082!
      - docker build -t first-nginx .
      - docker images
      - docker tag first-nginx $DOCKER_USERNAME/first-nginx
      - docker push $DOCKER_USERNAME/first-nginx
    